/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_AppComponent,
  data: {}
}
);
export function View_AppComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[(l()(),import0.ɵted((null as any),['app component']))],(null as any),(null as any));
}
function View_AppComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),(null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
    import0.ɵdid(24576,(null as any),0,import1.AppComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const AppComponentNgFactory:import0.ComponentFactory<import1.AppComponent> = import0.ɵccf('app-root',import1.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2xhY28vV29ya3MvdG1wL25ncmVwcm8tMDAwMS9zcmMvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9sYWNvL1dvcmtzL3RtcC9uZ3JlcHJvLTAwMDEvc3JjL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9sYWNvL1dvcmtzL3RtcC9uZ3JlcHJvLTAwMDEvc3JjL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9sYWNvL1dvcmtzL3RtcC9uZ3JlcHJvLTAwMDEvc3JjL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiYXBwIGNvbXBvbmVudCIsIjxhcHAtcm9vdD48L2FwcC1yb290PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5QkNBQTs7OztJQ0FBO2dCQUFBOzs7OyJ9
